
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-amqp-nodeport
spec:
  type: NodePort
  selector:
    app: rabbit-mq
  ports:
    - name: amqp
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30011
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  ports:
  - port: 5672
    name: port1
  - port: 5674
    name: port2
  selector:
    app: rabbit-mq
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbit-mq
  name: rabbit-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      labels:
         app: rabbit-mq
    spec:
      containers:
      - image: cristiancune/rabbit-cinema:latest
        name: rabbit-mq
        ports:
        - containerPort: 15672
        - containerPort: 5672
        - containerPort: 5674
        volumeMounts:
        - name: rabbit-persistent-storage
          mountPath: /var/lib/rabbitmq/mnesia/
      volumes:
      - name: rabbit-persistent-storage
        persistentVolumeClaim:
          claimName: rabbit-mq-data     