apiVersion: v1
kind: Service
metadata:
  name: api-service-nodeport
spec:
  type: NodePort
  selector:
    app: spring-cinema-api
  ports:
    - name: api-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-cinema-api
spec:
  selector:
    matchLabels:
      app: spring-cinema-api
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-cinema-api
    spec:
      containers:
        - name: spring-cinema-api
          image: cristiancune/cinema-api:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster