apiVersion: v1
kind: Service
metadata:
  name: api-service-nodeport
spec:
  type: NodePort
  selector:
    app: spring-cinema-api
  ports:
    - name: api-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-cinema-api
spec:
  selector:
    matchLabels:
      app: spring-cinema-api
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-cinema-api
    spec:
      containers:
        - name: spring-cinema-api
          image: cristiancune/cinema-api:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
          env:
            - name: SPRING_RABBITMQ_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  name: cinema-config
                  key: SPRING_RABBITMQ_ADDRESSES
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cinema-secret
                  key: SPRING_RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cinema-secret
                  key: SPRING_RABBITMQ_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: cinema-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cinema-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cinema-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              valueFrom:
                configMapKeyRef:
                  name: cinema-config
                  key: SPRING_DATASOURCE_DRIVER-CLASS-NAME