version: '3.3'

services:
  mysql_cinema:
    container_name: "mysql_cinema"
    image: mysql:8.0
    volumes:
    - my_db_data:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - network-api-db
      - network-db-adminer
  adminer_container:
    image: adminer:4.7
    environment:
      ADMINER_DEFAULT_SERVER: mysql_cinema
    ports:
    - "8000:8080"
    networks:
      - network-db-adminer
  cinema_api:
    image: andreicune/img_repo
    ports:
    - "8080:8080"
    networks:
      - network-api-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_cinema:3306/cinema
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - "mysql_cinema"
    restart: on-failure

networks:
  network-api-db:
  network-db-adminer:
volumes:
  my_db_data: {}