spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meteo?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
