server:
  port: 8081
spring:
  rabbitmq:
    addresses: rabbit:5674,rabbit:5672
    username: guest
    password: guest
    virtual-host: malima
  datasource:
    url: jdbc:mysql://mysql:3306/cinema_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update